package risk.Enums;

public enum GameStatusEnum {
    TROOP_PLACEMENT_PHASE,
    SELECT_ATTACKING_COUNTRY_PHASE,
    SELECT_DEFENDING_COUNTRY_PHASE,
    SELECT_TROOP_MOVING_FROM_PHASE,
    SELECT_TROOP_MOVING_TO_PHASE,
    WAITING;
}
